### PR TITLE
add install font script

### PR DESCRIPTION
**Pull request by james2doyle**

### CODE REVIEW

**Comment by jordwalke** [comment]
These diffs are awesome - I'll merge them in pretty soon. It would be so cool if we could get the installation down to "one click" essentially.

**Comment by james2doyle** [comment]
It would be possible. Also I think reversing the process would be good as well. Like undoing the any links and restoring the backups

**Comment by jordwalke** [comment]
Oh totally.

**Comment by james2doyle** [comment]
Do you want me to just make one big install script?

**Comment by jordwalke** [comment]
Sounds great!

**Comment by jordwalke** [comment]
Curious, is there no way to install a font via a script without having the user click "Install"?

**Comment by james2doyle** [comment]
Maybe you could have it moved to the fonts folder? Not sure

**Comment by jordwalke** [comment]
Feel free to close these other PRs out.

**Pull request closed without merging**
