### PR TITLE
4. Start MacVim clarification

### PR DESCRIPTION
**Pull request by idkjs**
I had to think about that for a second. tried running some command in terminal then realised instruction must have meant the app.

### CODE REVIEW

**Comment by jordwalke** [comment]
I actually think that MacVim doesn't install the binary `mvim` by default. I (and probably you) happen to have the binary installed from a previous install?

**Comment by idkjs** [comment]
Not fluent in bash but looks like it does, in fact, install it so both commands would be available. Terminal output below. 

From playing with it, if you do step 4, but before step 5, if you have a .vim/.vimrc file previously existing, the `mvim` command will hit those vim configs and through errors where as `$ open /Applications/MacVim.app`, will not.  Might be enough to just leave this here instead of changing the instructions....

```sh
shingdev at cosmos in ~
$ mvim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 21 2017 13:18:42)
MacOS X (unix) version
Included patches: 1-1130
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +find_in_path    -mouse_sysmouse  -tag_any_white
...

shingdev at cosmos in ~
$ brew remove macvim
Uninstalling /usr/local/Cellar/macvim/HEAD-5cba1fc... (2,138 files, 34MB)

shingdev at cosmos in ~
$ mvim --version
-bash: /usr/local/bin/mvim: No such file or directory

shingdev at cosmos in ~
$ brew install macvim
/usr/local/Homebrew/Library/Taps/tavianator/homebrew-tap/.git/FETCH_HEAD Stats {
...
  birthtime: 2017-08-24T06:08:06.000Z }
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
cmake ✔

==> Downloading https://homebrew.bintray.com/bottles/macvim-8.0-137.high_sierra.bottle.tar.gz
Already downloaded: /Users/shingdev/Library/Caches/Homebrew/macvim-8.0-137.high_sierra.bottle.tar.gz
==> Pouring macvim-8.0-137.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/macvim/8.0-137: 2,137 files, 34MB

shingdev at cosmos in ~
$ mvim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 17 2017 21:34:25)
MacOS X (unix) version
Included patches: 1-1098
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
...
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/opt/python/Frameworks -I/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib -F/usr/local/opt/python/Frameworks -L/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/opt/python/Frameworks -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby

shingdev at cosmos in ~
$ brew remove macvim
Uninstalling /usr/local/Cellar/macvim/8.0-137... (2,137 files, 34MB)

shingdev at cosmos in ~
$ mvim
-bash: /usr/local/bin/mvim: No such file or directory

shingdev at cosmos in ~
$ mvim --version
-bash: /usr/local/bin/mvim: No such file or directory

```

**Comment by jordwalke** [comment]
Oh, you installed MacVim via brew which put mvim in your path. Not everyone installs MacVim via brew (I download the release from the MacVim page).

**Comment by idkjs** [comment]
Ah! So installing direct from source is recommended. Let me go research why that is. Thank you.

**Comment by jordwalke** [comment]
I recommend just installing MacVim via the official released versions in the macvim-dev repo.

**Pull request closed without merging**
